apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dcl0p9umx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dcl0p9umx-go 
  name: dcl0p9umx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dcl0p9umx-go 
