apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dcl0p9umx-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtaptestqa/rhtap-qe:58f2b2ad494eca536b35b14fcf327dfe76690d5f@sha256:06b05a63bf00e8e3023888d77bf140987f5435384aa1353d501c6cf6dfd58ee8
          name: container-image
